name: Event Trigger Practice

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      user:
        description: 'Enter your name'
        required: true

jobs:
  greet_job:
    runs-on: self-hosted
    name: Greet User
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run greeting docker action
        uses: ./my-docker-action
        id: greet
        with:
          person-name: ${{ github.event.inputs.user || 'AutoUser' }}

      - name: Print output
        run: echo "Greeting message: ${{ steps.greet.outputs.greeting }}"

  node_test_job:
    name: Matrix Node.js Test
    needs: greet_job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Log from matrix job
        run: |
          echo "This is Node version ${{ matrix.node }}"
          echo "Workflow triggered by: ${{ github.event_name }}"
