name: Custom Docker Action Example

on: push

jobs:
  greet_job:
    runs-on: self-hosted
    name: Say Hello with Custom Docker Action
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run my docker action
        uses: ./my-docker-action
        id: greet_step
        with:
          person-name: "Yash"
      - name: Show greeting output
        run: echo "Message from action:${{ steps.greet_step.outputs.greeting }}"
