name: Custom Docker Action Example

on: push

jobs:
  greet_job:
    runs-on: self-hosted
    name: Say Hello with Custom Docker Action

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker image without cache
        run: docker build --no-cache -t my-action ./my-docker-action

      - name: Run Docker container with inputs
        run: |
          docker run --rm \
            -e INPUT_PERSON-NAME="Yash" \
            -v ${{ github.workspace }}:/github/workspace \
            my-action
